version: "2"
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./raptor-auth-service/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor

  couchbase:
    container_name: couchbase
    image: couchbase/server
    volumes:
      - ./data/couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5
    command: elasticsearch -E cluster.name="raptor" -E path.data=/usr/share/elasticsearch/data
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
