
#TODO: Add Auth Service + Broker API

db:
  image: mariadb:latest
  container_name: raptorauthdb
  ports:
    - 3306:3306
  volumes:
    - ./data/mariadb:/var/lib/mysql
  environment:
    # MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor
    PMA_HOST: mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: raptormyadmin
  links:
    - db:mysql
  restart: always
  ports:
    - 10080:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: raptor
    MYSQL_DATABASE: raptor

couchbase1:
  image: couchbase/server
  container_name: raptorcouchbase1
  volumes:
    - ./data/couchbase1:/opt/couchbase/var
  ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 11210:11210
