version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  api:
    build: ./raptor-http-api
    container_name: raptor-http-api
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch
      - couchbase
    networks:
      - raptor_net

  broker:
    build: ./raptor-broker
    container_name: raptor-broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch
    networks:
      - raptor_net

  auth:
    build: ./raptor-auth-service
    container_name: raptor-auth-service
    ports:
      - 8090:8090
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - mariadb
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net

  couchbase:
    image: couchbase/server
    volumes:
      - ./data/couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - raptor_net

  elasticsearch:
    image: elasticsearch:5
    command: elasticsearch -E cluster.name="raptor" -E path.data=/usr/share/elasticsearch/data
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - raptor_net

  proxy:
    build: ./docker/proxy
    ports:
      - 80:80
    depends_on:
      - api
      - auth
      - broker
    networks:
      - raptor_net
