# define the type of auth: token, allow_all
type: token
cache: memory
token:
  truststore:
    path: /etc/raptor/truststore
    password: passwd
  checkUrl: https://frontend.raptor.local/api/token/check
  syncUrl: https://frontend.raptor.local/api/device/sync
