type: elasticsearch
elasticsearch:
  type: transport
  clientConfig:
    cluster.name: raptor
  transport:
    host: 127.0.0.1
    port: 9300
  indices:
    source: /etc/raptor/indices.json
    names:
      object:
        index: sodescriptions
        type: serviceobject
      data:
        index: soupdates
        type: update
      subscriptions:
        index: subscriptions
        type: subscription
      groups:
        index: sodescriptions
        type: ParentObject
