
type: mapdb

mapdb:
  storage: file # or memory
  storePath: /tmp/raptor
  indices:
    objects:
      - [userId]
    data:
      - [userId]
      - [userId, streamId]
      - [userId, objectId]
      - [userId, objectId, streamId]
    actuations:
      - [userId]

couchbase:
  nodes:
    - raptor.local
  username: admin
  password: password
  bucketDefaults:
    password: ""
    quota: 360
    replica: 0
    indexReplica: false
    enableFlush: false

  bucketsIndex:
    objects:
      - [userId]
    data:
      - [userId]
      - [userId, streamId]
      - [userId, objectId]
      - [userId, objectId, streamId]
    actuations:
      - [userId]

  buckets:
    # Configure couchbase bucket name
    objects: raptor-objects
    data: raptor-data
    actuations: raptor-actions
