
type: couchbase
couchbase:
  nodes:
    - raptor.local

  username: Administrator
  password: password

  bucketDefaults:
    password: mybucket
    quota: 360
    replica: 0
    indexReplica: false
    enableFlush: false

  bucketsIndex:
    objects:
      - [userId]
    data:
      - [userId]
      - [userId, streamId]
      - [userId, objectId]
    actuations:
      - [userId]

  buckets:
    # Configure couchbase bucket name
    objects: serviceobjects
    data: soupdates
    actuations: actuations
